name: Tests with pytest and C test suite

on:
  pull_request:
    paths:
      - 'pycla/**'
      - 'cla/**'
      - 'test/**'
      - '.github/**'

jobs:
  run_tests:
    permissions:
      contents: 'write'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout to source branch
        uses: actions/checkout@v3

      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: Setup CMake and Ninja
        uses: lukka/get-cmake@v4
        with:
          cmakeVersion: ^4.0.0
          useCloudCache: false
          useLocalCache: false

      - name: Setup Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Build and test cla (C API)
        run: |
          make test

      - name: Prepare environment for pycla (Python API)
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r py-dev-requirements.txt
          python -m pip install -e .
  
      - name: Run tests with pytest for pycla
        run: pytest -x test/python
